# Generated by Django 4.2.5 on 2024-06-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('system', '0002_alter_customer_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidates',
        ),
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer', verbose_name='HR')),
            ],
            options={
                'verbose_name': 'HR',
                'verbose_name_plural': 'HRs',
                'db_table': 'hr',
                'ordering': ('id',),
            },
        ),
    ]
