# Generated by Django 4.2.5 on 2024-06-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0002_alter_customer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Предыдущее место работы')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(verbose_name='Дата конца работы')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer', verbose_name='Кандидат')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100, verbose_name='Университет')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.spec', verbose_name='Специальность')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer', verbose_name='Кандидат')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_min', models.IntegerField(verbose_name='Минимальная зарплата')),
                ('salary_max', models.IntegerField(verbose_name='Максимальная зарплата')),
                ('created', models.DateTimeField(verbose_name='Создан')),
                ('applicant_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.spec', verbose_name='Специальность')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer', verbose_name='Кандидат')),
            ],
        ),
    ]
